apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: receiver-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: receiver.${PUBLIC_IP}.nip.io
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: receiver-service
                port:
                  number: 80
