apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: hashicorp/http-echo
          args:
            - "-text=Hello, World!"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: receiver
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5678
      