services:

  scrapper_mongo_db:
    container_name: scrapper_mongo_db
    image: mongo:latest
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - scraper_mongo_db_container:/data/db
    networks:
      scraper_network:
        ipv4_address: 218.45.0.2

  scrapper_rabbit_mq:
    container_name: scrapper_rabbit_mq
    image: rabbitmq:management
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      scraper_network:
        ipv4_address: 218.45.0.3

volumes:
  scraper_mongo_db_container:

networks:
  scraper_network:
    ipam:
      driver: default
      config:
        - subnet: 218.45.0.0/16