name: Kind Integration Tests

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  kind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.23.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Verify Kubernetes Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A

      - name: Debugging - List all resources
        run: |
          kubectl get all --all-namespaces

      - name: Deploy MongoDB
        run: kubectl apply -f k8s/mongo-deployment.yml

      - name: Wait for MongoDB pod to be ready
        run: |
          echo "Waiting for MongoDB pod to be ready..."
          kubectl wait --for=condition=Ready pod -l app=mongo --timeout=120s
          echo "MongoDB pod is ready."

      - name: MongoDB readiness check
        run: |
          echo "Checking if MongoDB is ready..."
          until kubectl exec $(kubectl get pod -l app=mongo -o jsonpath="{.items[0].metadata.name}") -- mongosh --eval "db.runCommand({ ping: 1 })"; do
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done
          echo "MongoDB is ready."   

      - name: Debugging - List all pods
        run: |
          kubectl get pods --all-namespaces          
