name: Kind Integration Tests

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  kind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.23.0

      - name: Create Kind cluster
        run: kind create cluster --wait 60s

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Verify Kubernetes Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A
